### ISSUE TITLE
Assertion failed on parsing malformed SML file (main/parse.c:1372)

### ISSUE THREAD

**Issue by kcwu** [universal-ctags/ctags#528]
How to reproduce:
```
$ echo and > and.sml
$ ctags and.sml
ctags: main/parse.c:1372: boolean isLanguageKindEnabled(const langType, char): Assertion `kindOpt' failed.
ctags: main/parse.c:1372: parsing and.sml:1 as SML
Aborted
```

this issue is found by afl-fuzz

**Comment by masatake** [comment]
It seems that this one is already fixed in 
```
commit 4a95e4a55f67230fc4eee91ffb31c18c422df6d3
Author: Colomban Wendling <ban@herbesfolles.org>
Date:   Mon May 18 20:11:49 2015 +0200

    Do not generate tags for disabled kinds
    
    Closes #324.
```

**Comment by kcwu** [comment]
I can still reproduce this using latest master 13ea82733c8f55c1aad6ceb159da8cef5fc81782

**Comment by masatake** [comment]
... I have no idea. Can I ask you to get a backtrace with gdb?

**Comment by kcwu** [comment]
I found I can reproduce it with clang but not with gcc. The problem is
```
 72| static void makeSmlTag (smlKind type, vString *name)
 73| {
 74|         tagEntryInfo tag;
 75|
 76|         if (! SmlKinds [type].enabled)
 77|                 return;
 ```
where type = K_NONE = -1.
It's out of bound access for SmlKinds[-1] and thus depends on memory layout.

**Comment by masatake** [comment]
Oh, I see. Thank you. I will try to fix this.
